AllCops:
  Exclude:
    - 'test/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
